# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: H-K's blog
email: kimhoon73@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I share the skills I have experienced while developing.
  And I wish these would be a help for someone.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kimhoon73
github_username:  hoon-kim
# Build settings
markdown: kramdown
# theme: minima

# theme: jekyll-theme-hacker
# theme: jekyll-theme-primer


plugins:
  - jekyll-feed
  - jekyll-toc # added by kimhoon

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


repository: "username/repo-name" # No repo name found. Specify using PAGES_REPO_NWO environment variables, ... ERROR

permalink: /:categories/:title

collections:
  docs:
    output: true
    permalink: /:collection/:name

# added by kimhoon
toc:
  min_level: 2
  max_level: 4


# algolia
algolia:
  application_id: ZO8LXX7OLM
  index_name:     jekyll # You can replace that with whatever name you want
  search_only_api_key: f56b4f49e9f6a68d6b042b8c7bc4e3d8
  files_to_exclude:
    - category/*.html
    - search
